package cs.sicnu.fiveg.mapper;

import cs.sicnu.fiveg.pojo.BlogDetails;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BlogDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_details
     *
     * @mbg.generated
     */
    int insert(BlogDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_details
     *
     * @mbg.generated
     */
    List<BlogDetails> selectAll();


    int selectBlogCount(BlogDetails details);

    List<BlogDetails> selectAllWithUserInfo();

    int updateRead(@Param("id")int blogId);

    /**
     *
     * @return
     */
    List<BlogDetails> selectByInfo(BlogDetails details);

    /**
     * @param  details
     * @param start 起始的下标
     * @param size 每一页的数目
     * @return 查询的结果 此处带用户名
     */
    List<BlogDetails> selectPaged(@Param("details") BlogDetails details, @Param("pageof") int pageof,@Param("size") int size);

    int update(@Param("blogDetails")BlogDetails details);

    BlogDetails selectPrevBlog(@Param("id") int blogId);

    BlogDetails selectNextBlog(@Param("id") int blogId);
}