package cs.sicnu.fiveg.mapper;

import cs.sicnu.fiveg.pojo.EmailVertification;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface EmailVertificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_vertification
     *
     * @mbg.generated
     */
    int insert(EmailVertification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_vertification
     *
     * @mbg.generated
     */
    List<EmailVertification> selectAll();

    int setVailed(@Param("email") String email);

    EmailVertification selectVild(@Param("email") String emial);
}