package cs.sicnu.fiveg.mapper;

import cs.sicnu.fiveg.pojo.MessageArea;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MessageAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_area
     *
     * @mbg.generated
     */
    int insert(MessageArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_area
     *
     * @mbg.generated
     */
    List<MessageArea> selectAll(@Param("belongid") int belongId);


    MessageArea selectNew();
}