package cs.sicnu.fiveg.mapper;

import cs.sicnu.fiveg.pojo.ReleaseFeature;

import java.util.List;

public interface ReleaseFeatureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release_feature
     *
     * @mbg.generated
     */
    int insert(ReleaseFeature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release_feature
     *
     * @mbg.generated
     */
    List<ReleaseFeature> selectAll();

    ReleaseFeature selectById(int id);

    ReleaseFeature selectLatest();

    int update(ReleaseFeature releaseFeature);
}