package cs.sicnu.fiveg.mapper;

import cs.sicnu.fiveg.pojo.VisitTotal;
import org.apache.ibatis.annotations.Param;
import org.springframework.web.bind.annotation.PostMapping;

import java.util.Date;


public interface VisitTotalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_total
     *
     * @mbg.generated
     */
    int insert(VisitTotal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_total
     *
     * @mbg.generated
     */
    int selectAll(int id);

    VisitTotal selectByDate(@Param("date") Date date);

    /**
     *
     * @param visitTotal id 此处必须设置 这里id 是where 条件
     *                   其余的属性 如果设置了 那么就是要更新的属性
     *                   否则忽略
     * @return
     */

    int updateById(@Param("id") int id);

    int updateByDate(@Param("date") Date date);

    VisitTotal select(@Param("id") int id);

    Integer selectById(@Param("id") int id);
}