package cs.sicnu.fiveg.pojo;

import java.util.Date;

public class ArticleCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_category.category_id
     *
     * @mbg.generated
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_category.category_name
     *
     * @mbg.generated
     */
    private String categoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_category.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_category.category_delete
     *
     * @mbg.generated
     */
    private Integer categoryDelete;

    private Integer statisticalNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_category.category_id
     *
     * @return the value of article_category.category_id
     *
     * @mbg.generated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_category.category_id
     *
     * @param categoryId the value for article_category.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_category.category_name
     *
     * @return the value of article_category.category_name
     *
     * @mbg.generated
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_category.category_name
     *
     * @param categoryName the value for article_category.category_name
     *
     * @mbg.generated
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_category.create_date
     *
     * @return the value of article_category.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_category.create_date
     *
     * @param createDate the value for article_category.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_category.category_delete
     *
     * @return the value of article_category.category_delete
     *
     * @mbg.generated
     */
    public Integer getCategoryDelete() {
        return categoryDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_category.category_delete
     *
     * @param categoryDelete the value for article_category.category_delete
     *
     * @mbg.generated
     */
    public void setCategoryDelete(Integer categoryDelete) {
        this.categoryDelete = categoryDelete;
    }
}