package cs.sicnu.fiveg.pojo;

import java.util.Date;

public class BlogDetails {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_details.blog_id
     *
     * @mbg.generated
     */
    private Integer blogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_details.blog_title
     *
     * @mbg.generated
     */
    private String blogTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_details.blog_author
     *
     * @mbg.generated
     */
    private UserInfo blogAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_details.blog_date
     *
     * @mbg.generated
     */
    private Date blogDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_details.blog_read
     *
     * @mbg.generated
     */
    private Integer blogRead;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_details.blog_summary
     *
     * @mbg.generated
     */
    private String blogSummary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_details.blog_label
     *
     * @mbg.generated
     */
    private String blogLabel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_details.blog_delete
     *
     * @mbg.generated
     */
    private Integer blogDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_details.blog_category
     *
     * @mbg.generated
     */
    private Integer blogCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_details.blog_html_content
     *
     * @mbg.generated
     */
    private String blogHtmlContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_details.blog_md_content
     *
     * @mbg.generated
     */
    private String blogMdContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_details.blog_id
     *
     * @return the value of blog_details.blog_id
     *
     * @mbg.generated
     */
    public Integer getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_details.blog_id
     *
     * @param blogId the value for blog_details.blog_id
     *
     * @mbg.generated
     */
    public void setBlogId(Integer blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_details.blog_title
     *
     * @return the value of blog_details.blog_title
     *
     * @mbg.generated
     */
    public String getBlogTitle() {
        return blogTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_details.blog_title
     *
     * @param blogTitle the value for blog_details.blog_title
     *
     * @mbg.generated
     */
    public void setBlogTitle(String blogTitle) {
        this.blogTitle = blogTitle == null ? null : blogTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_details.blog_author
     *
     * @return the value of blog_details.blog_author
     *
     * @mbg.generated
     */
    public Integer getBlogAuthorId(){
        return blogAuthor.getUserId();
    }


    public UserInfo getBlogAuthor() {
        return blogAuthor;
    }
    public String getBlogAuthorName(){
        return blogAuthor==null?null:blogAuthor.getUserName();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_details.blog_author
     *
     * @param blogAuthor the value for blog_details.blog_author
     *
     * @mbg.generated
     */
    public void setBlogAuthor(UserInfo blogAuthor) {
        this.blogAuthor = blogAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_details.blog_date
     *
     * @return the value of blog_details.blog_date
     *
     * @mbg.generated
     */
    public Date getBlogDate() {
        return blogDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_details.blog_date
     *
     * @param blogDate the value for blog_details.blog_date
     *
     * @mbg.generated
     */
    public void setBlogDate(Date blogDate) {
        this.blogDate = blogDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_details.blog_read
     *
     * @return the value of blog_details.blog_read
     *
     * @mbg.generated
     */
    public Integer getBlogRead() {
        return blogRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_details.blog_read
     *
     * @param blogRead the value for blog_details.blog_read
     *
     * @mbg.generated
     */
    public void setBlogRead(Integer blogRead) {
        this.blogRead = blogRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_details.blog_summary
     *
     * @return the value of blog_details.blog_summary
     *
     * @mbg.generated
     */
    public String getBlogSummary() {
        return blogSummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_details.blog_summary
     *
     * @param blogSummary the value for blog_details.blog_summary
     *
     * @mbg.generated
     */
    public void setBlogSummary(String blogSummary) {
        this.blogSummary = blogSummary == null ? null : blogSummary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_details.blog_label
     *
     * @return the value of blog_details.blog_label
     *
     * @mbg.generated
     */
    public String getBlogLabel() {
        return blogLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_details.blog_label
     *
     * @param blogLabel the value for blog_details.blog_label
     *
     * @mbg.generated
     */
    public void setBlogLabel(String blogLabel) {
        this.blogLabel = blogLabel == null ? null : blogLabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_details.blog_delete
     *
     * @return the value of blog_details.blog_delete
     *
     * @mbg.generated
     */
    public Integer getBlogDelete() {
        return blogDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_details.blog_delete
     *
     * @param blogDelete the value for blog_details.blog_delete
     *
     * @mbg.generated
     */
    public void setBlogDelete(Integer blogDelete) {
        this.blogDelete = blogDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_details.blog_category
     *
     * @return the value of blog_details.blog_category
     *
     * @mbg.generated
     */
    public Integer getBlogCategory() {
        return blogCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_details.blog_category
     *
     * @param blogCategory the value for blog_details.blog_category
     *
     * @mbg.generated
     */
    public void setBlogCategory(Integer blogCategory) {
        this.blogCategory = blogCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_details.blog_html_content
     *
     * @return the value of blog_details.blog_html_content
     *
     * @mbg.generated
     */
    public String getBlogHtmlContent() {
        return blogHtmlContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_details.blog_html_content
     *
     * @param blogHtmlContent the value for blog_details.blog_html_content
     *
     * @mbg.generated
     */
    public void setBlogHtmlContent(String blogHtmlContent) {
        this.blogHtmlContent = blogHtmlContent == null ? null : blogHtmlContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_details.blog_md_content
     *
     * @return the value of blog_details.blog_md_content
     *
     * @mbg.generated
     */
    public String getBlogMdContent() {
        return blogMdContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_details.blog_md_content
     *
     * @param blogMdContent the value for blog_details.blog_md_content
     *
     * @mbg.generated
     */
    public void setBlogMdContent(String blogMdContent) {
        this.blogMdContent = blogMdContent == null ? null : blogMdContent.trim();
    }
}