package cs.sicnu.fiveg.pojo;

import java.util.Date;

public class CodeLibrary {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_library.code_id
     *
     * @mbg.generated
     */
    private Integer codeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_library.code_title
     *
     * @mbg.generated
     */
    private String codeTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_library.code_author
     *
     * @mbg.generated
     */
    private UserInfo codeAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_library.code_date
     *
     * @mbg.generated
     */
    private Date codeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_library.code_read
     *
     * @mbg.generated
     */
    private Integer codeRead;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_library.code_summary
     *
     * @mbg.generated
     */
    private String codeSummary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_library.code_label
     *
     * @mbg.generated
     */
    private String codeLabel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_library.code_delete
     *
     * @mbg.generated
     */
    private Integer codeDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_library.code_category
     *
     * @mbg.generated
     */
    private Integer codeCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_library.code_html_content
     *
     * @mbg.generated
     */
    private String codeHtmlContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_library.code_md_content
     *
     * @mbg.generated
     */
    private String codeMdContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_library.code_id
     *
     * @return the value of code_library.code_id
     *
     * @mbg.generated
     */
    public Integer getCodeId() {
        return codeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_library.code_id
     *
     * @param codeId the value for code_library.code_id
     *
     * @mbg.generated
     */
    public void setCodeId(Integer codeId) {
        this.codeId = codeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_library.code_title
     *
     * @return the value of code_library.code_title
     *
     * @mbg.generated
     */
    public String getCodeTitle() {
        return codeTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_library.code_title
     *
     * @param codeTitle the value for code_library.code_title
     *
     * @mbg.generated
     */
    public void setCodeTitle(String codeTitle) {
        this.codeTitle = codeTitle == null ? null : codeTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_library.code_author
     *
     * @return the value of code_library.code_author
     *
     * @mbg.generated
     */
    public UserInfo getCodeAuthor() {
        return codeAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_library.code_author
     *
     * @param codeAuthor the value for code_library.code_author
     *
     * @mbg.generated
     */
    public void setCodeAuthor(UserInfo codeAuthor) {
        this.codeAuthor = codeAuthor;
    }


    public Integer getCodeAuthorId (){ return this.codeAuthor.getUserId();}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_library.code_date
     *
     * @return the value of code_library.code_date
     *
     * @mbg.generated
     */
    public Date getCodeDate() {
        return codeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_library.code_date
     *
     * @param codeDate the value for code_library.code_date
     *
     * @mbg.generated
     */
    public void setCodeDate(Date codeDate) {
        this.codeDate = codeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_library.code_read
     *
     * @return the value of code_library.code_read
     *
     * @mbg.generated
     */
    public Integer getCodeRead() {
        return codeRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_library.code_read
     *
     * @param codeRead the value for code_library.code_read
     *
     * @mbg.generated
     */
    public void setCodeRead(Integer codeRead) {
        this.codeRead = codeRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_library.code_summary
     *
     * @return the value of code_library.code_summary
     *
     * @mbg.generated
     */
    public String getCodeSummary() {
        return codeSummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_library.code_summary
     *
     * @param codeSummary the value for code_library.code_summary
     *
     * @mbg.generated
     */
    public void setCodeSummary(String codeSummary) {
        this.codeSummary = codeSummary == null ? null : codeSummary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_library.code_label
     *
     * @return the value of code_library.code_label
     *
     * @mbg.generated
     */
    public String getCodeLabel() {
        return codeLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_library.code_label
     *
     * @param codeLabel the value for code_library.code_label
     *
     * @mbg.generated
     */
    public void setCodeLabel(String codeLabel) {
        this.codeLabel = codeLabel == null ? null : codeLabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_library.code_delete
     *
     * @return the value of code_library.code_delete
     *
     * @mbg.generated
     */
    public Integer getCodeDelete() {
        return codeDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_library.code_delete
     *
     * @param codeDelete the value for code_library.code_delete
     *
     * @mbg.generated
     */
    public void setCodeDelete(Integer codeDelete) {
        this.codeDelete = codeDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_library.code_category
     *
     * @return the value of code_library.code_category
     *
     * @mbg.generated
     */
    public Integer getCodeCategory() {
        return codeCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_library.code_category
     *
     * @param codeCategory the value for code_library.code_category
     *
     * @mbg.generated
     */
    public void setCodeCategory(Integer codeCategory) {
        this.codeCategory = codeCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_library.code_html_content
     *
     * @return the value of code_library.code_html_content
     *
     * @mbg.generated
     */
    public String getCodeHtmlContent() {
        return codeHtmlContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_library.code_html_content
     *
     * @param codeHtmlContent the value for code_library.code_html_content
     *
     * @mbg.generated
     */
    public void setCodeHtmlContent(String codeHtmlContent) {
        this.codeHtmlContent = codeHtmlContent == null ? null : codeHtmlContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_library.code_md_content
     *
     * @return the value of code_library.code_md_content
     *
     * @mbg.generated
     */
    public String getCodeMdContent() {
        return codeMdContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_library.code_md_content
     *
     * @param codeMdContent the value for code_library.code_md_content
     *
     * @mbg.generated
     */
    public void setCodeMdContent(String codeMdContent) {
        this.codeMdContent = codeMdContent == null ? null : codeMdContent.trim();
    }
}