package cs.sicnu.fiveg.pojo;

import java.util.Date;

public class EmailVertification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_vertification.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_vertification.vaild
     *
     * @mbg.generated
     */
    private Integer vaild;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_vertification.email_address
     *
     * @mbg.generated
     */
    private String emailAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_vertification.email_date
     *
     * @mbg.generated
     */
    private Date emailDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_vertification.vrtificationcode
     *
     * @mbg.generated
     */
    private String vrtificationcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_vertification.id
     *
     * @return the value of email_vertification.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_vertification.id
     *
     * @param id the value for email_vertification.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_vertification.vaild
     *
     * @return the value of email_vertification.vaild
     *
     * @mbg.generated
     */
    public Integer getVaild() {
        return vaild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_vertification.vaild
     *
     * @param vaild the value for email_vertification.vaild
     *
     * @mbg.generated
     */
    public void setVaild(Integer vaild) {
        this.vaild = vaild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_vertification.email_address
     *
     * @return the value of email_vertification.email_address
     *
     * @mbg.generated
     */
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_vertification.email_address
     *
     * @param emailAddress the value for email_vertification.email_address
     *
     * @mbg.generated
     */
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress == null ? null : emailAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_vertification.email_date
     *
     * @return the value of email_vertification.email_date
     *
     * @mbg.generated
     */
    public Date getEmailDate() {
        return emailDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_vertification.email_date
     *
     * @param emailDate the value for email_vertification.email_date
     *
     * @mbg.generated
     */
    public void setEmailDate(Date emailDate) {
        this.emailDate = emailDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_vertification.vrtificationcode
     *
     * @return the value of email_vertification.vrtificationcode
     *
     * @mbg.generated
     */
    public String getVrtificationcode() {
        return vrtificationcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_vertification.vrtificationcode
     *
     * @param vrtificationcode the value for email_vertification.vrtificationcode
     *
     * @mbg.generated
     */
    public void setVrtificationcode(String vrtificationcode) {
        this.vrtificationcode = vrtificationcode == null ? null : vrtificationcode.trim();
    }
}