package cs.sicnu.fiveg.pojo;

import java.util.Date;

public class FileDownload {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_download.file_id
     *
     * @mbg.generated
     */
    private Integer fileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_download.file_name
     *
     * @mbg.generated
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_download.file_url
     *
     * @mbg.generated
     */
    private String fileUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_download.file_upload_date
     *
     * @mbg.generated
     */
    private Date fileUploadDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_download.file_download_count
     *
     * @mbg.generated
     */
    private Integer fileDownloadCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_download.file_id
     *
     * @return the value of file_download.file_id
     *
     * @mbg.generated
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_download.file_id
     *
     * @param fileId the value for file_download.file_id
     *
     * @mbg.generated
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_download.file_name
     *
     * @return the value of file_download.file_name
     *
     * @mbg.generated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_download.file_name
     *
     * @param fileName the value for file_download.file_name
     *
     * @mbg.generated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_download.file_url
     *
     * @return the value of file_download.file_url
     *
     * @mbg.generated
     */
    public String getFileUrl() {
        return fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_download.file_url
     *
     * @param fileUrl the value for file_download.file_url
     *
     * @mbg.generated
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl == null ? null : fileUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_download.file_upload_date
     *
     * @return the value of file_download.file_upload_date
     *
     * @mbg.generated
     */
    public Date getFileUploadDate() {
        return fileUploadDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_download.file_upload_date
     *
     * @param fileUploadDate the value for file_download.file_upload_date
     *
     * @mbg.generated
     */
    public void setFileUploadDate(Date fileUploadDate) {
        this.fileUploadDate = fileUploadDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_download.file_download_count
     *
     * @return the value of file_download.file_download_count
     *
     * @mbg.generated
     */
    public Integer getFileDownloadCount() {
        return fileDownloadCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_download.file_download_count
     *
     * @param fileDownloadCount the value for file_download.file_download_count
     *
     * @mbg.generated
     */
    public void setFileDownloadCount(Integer fileDownloadCount) {
        this.fileDownloadCount = fileDownloadCount;
    }
}