package cs.sicnu.fiveg.pojo;

import java.util.Date;

public class MessageArea {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_area.message_id
     *
     * @mbg.generated
     */
    private Integer messageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_area.message_parent
     *
     * @mbg.generated
     */
    private Integer messageParent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_area.message_belong
     *
     * @mbg.generated
     */
    private Integer messageBelong;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_area.message_date
     *
     * @mbg.generated
     */
    private Date messageDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_area.message_email
     *
     * @mbg.generated
     */
    private String messageEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_area.message_username
     *
     * @mbg.generated
     */
    private UserInfo messageUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_area.message_content
     *
     * @mbg.generated
     */
    private String messageContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_area.message_id
     *
     * @return the value of message_area.message_id
     *
     * @mbg.generated
     */
    public Integer getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_area.message_id
     *
     * @param messageId the value for message_area.message_id
     *
     * @mbg.generated
     */
    public void setMessageId(Integer messageId) {
        this.messageId = messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_area.message_parent
     *
     * @return the value of message_area.message_parent
     *
     * @mbg.generated
     */
    public Integer getMessageParent() {
        return messageParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_area.message_parent
     *
     * @param messageParent the value for message_area.message_parent
     *
     * @mbg.generated
     */
    public void setMessageParent(Integer messageParent) {
        this.messageParent = messageParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_area.message_belong
     *
     * @return the value of message_area.message_belong
     *
     * @mbg.generated
     */
    public Integer getMessageBelong() {
        return messageBelong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_area.message_belong
     *
     * @param messageBelong the value for message_area.message_belong
     *
     * @mbg.generated
     */
    public void setMessageBelong(Integer messageBelong) {
        this.messageBelong = messageBelong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_area.message_date
     *
     * @return the value of message_area.message_date
     *
     * @mbg.generated
     */
    public Date getMessageDate() {
        return messageDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_area.message_date
     *
     * @param messageDate the value for message_area.message_date
     *
     * @mbg.generated
     */
    public void setMessageDate(Date messageDate) {
        this.messageDate = messageDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_area.message_email
     *
     * @return the value of message_area.message_email
     *
     * @mbg.generated
     */
    public String getMessageEmail() {
        return messageEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_area.message_email
     *
     * @param messageEmail the value for message_area.message_email
     *
     * @mbg.generated
     */
    public void setMessageEmail(String messageEmail) {
        this.messageEmail = messageEmail == null ? null : messageEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_area.message_username
     *
     * @return the value of message_area.message_username
     *
     * @mbg.generated
     */
    public UserInfo getMessageUser() {
        return messageUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_area.message_username
     *
     * @param messageUser the value for message_area.message_username
     *
     * @mbg.generated
     */
    public void setMessageUser(UserInfo messageUser) {
        this.messageUser = messageUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_area.message_content
     *
     * @return the value of message_area.message_content
     *
     * @mbg.generated
     */
    public String getMessageContent() {
        return messageContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_area.message_content
     *
     * @param messageContent the value for message_area.message_content
     *
     * @mbg.generated
     */
    public void setMessageContent(String messageContent) {
        this.messageContent = messageContent == null ? null : messageContent.trim();
    }
}