package cs.sicnu.fiveg.pojo;

import java.util.Date;

public class ReleaseFeature {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release_feature.release_id
     *
     * @mbg.generated
     */
    private Integer releaseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release_feature.release_author
     *
     * @mbg.generated
     */
    private String releaseAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release_feature.release_date
     *
     * @mbg.generated
     */
    private Date releaseDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release_feature.release_number
     *
     * @mbg.generated
     */
    private String releaseNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column release_feature.release_content
     *
     * @mbg.generated
     */
    private String releaseContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release_feature.release_id
     *
     * @return the value of release_feature.release_id
     *
     * @mbg.generated
     */
    public Integer getReleaseId() {
        return releaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release_feature.release_id
     *
     * @param releaseId the value for release_feature.release_id
     *
     * @mbg.generated
     */
    public void setReleaseId(Integer releaseId) {
        this.releaseId = releaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release_feature.release_author
     *
     * @return the value of release_feature.release_author
     *
     * @mbg.generated
     */
    public String getReleaseAuthor() {
        return releaseAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release_feature.release_author
     *
     * @param releaseAuthor the value for release_feature.release_author
     *
     * @mbg.generated
     */
    public void setReleaseAuthor(String releaseAuthor) {
        this.releaseAuthor = releaseAuthor == null ? null : releaseAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release_feature.release_date
     *
     * @return the value of release_feature.release_date
     *
     * @mbg.generated
     */
    public Date getReleaseDate() {
        return releaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release_feature.release_date
     *
     * @param releaseDate the value for release_feature.release_date
     *
     * @mbg.generated
     */
    public void setReleaseDate(Date releaseDate) {
        this.releaseDate = releaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release_feature.release_number
     *
     * @return the value of release_feature.release_number
     *
     * @mbg.generated
     */
    public String getReleaseNumber() {
        return releaseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release_feature.release_number
     *
     * @param releaseNumber the value for release_feature.release_number
     *
     * @mbg.generated
     */
    public void setReleaseNumber(String releaseNumber) {
        this.releaseNumber = releaseNumber == null ? null : releaseNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column release_feature.release_content
     *
     * @return the value of release_feature.release_content
     *
     * @mbg.generated
     */
    public String getReleaseContent() {
        return releaseContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column release_feature.release_content
     *
     * @param releaseContent the value for release_feature.release_content
     *
     * @mbg.generated
     */
    public void setReleaseContent(String releaseContent) {
        this.releaseContent = releaseContent == null ? null : releaseContent.trim();
    }
}